import {
    attribute,
    autoGeneratedHashKey,
    table
} from "@aws/dynamodb-data-mapper-annotations";
import { DynamoDB } from "aws-sdk";

const dateMarshall = (value: Date): DynamoDB.AttributeValue =>
    ({ S: value.toString() } as DynamoDB.AttributeValue);

const dateUnmarshall = ({ N }: DynamoDB.AttributeValue): Date | undefined =>
    N ? new Date(N) : undefined;

@table('transactions')
export class Transaction {
    @autoGeneratedHashKey()
    id?: string;

    @attribute()
    order_id?: number;

    @attribute()
    amount?: number;

    @attribute()
    proxy?: string;

    @attribute()
    reference?: string;

    @attribute()
    delivered?: boolean;

    @attribute({ marshall: dateMarshall, unmarshall: dateUnmarshall, defaultProvider: () => new Date() })
    created_at?: Date;

    @attribute({ marshall: dateMarshall, unmarshall: dateUnmarshall, defaultProvider: () => new Date() })
    updated_at?: Date;
}